### ISSUE TITLE
Install Perl along with MiKTeX to use latexmk

### ISSUE THREAD

**Issue by hjoeren** [MiKTeX/docker-miktex#1]
I just experimented with the MiKTeX docker image and tried to build a (simple hello-world) document with (installed) latexmk. This failed because one (or more) necessary perl module(s) are missing with the default ubuntu installation. The exact error message:

```
Can't locate File/Copy.pm in @INC (you may need to install the File::Copy module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /miktex/.miktex/texmfs/install/scripts/latexmk/latexmk.pl line 129.
BEGIN failed--compilation aborted at /miktex/.miktex/texmfs/install/scripts/latexmk/latexmk.pl line 129.
```

After that I adapted the MiKTeX image and installed perl with a successful PDF build:

```
FROM miktex/miktex

USER root

RUN apt-get update
RUN apt-get install -y perl

USER miktex
```

I think this could be a (small) improvment at least for using latexmk regarding the official image doesn't allow to install packages to ubuntu because of missing privileges.

**Comment by nanmu42** [comment]
Have met this too.

**Comment by edocevoli** [comment]
This has been fixed.
