### ISSUE TITLE
Update Docker Hub image (2.9.6980 -> 2.9.7050)

### ISSUE THREAD

**Issue by skyfrk** [MiKTeX/docker-miktex#13]
Hello there! Could you please release a fresh image to the Docker Hub?

I tried to use the docker hub image to build my document using: `docker run --rm -ti -v C:\some\path:/miktex/work miktex/miktex pdflatex root.tex`

But it failed while downloading some packages:

```
starting package maintenance...
installation directory: /miktex/.miktex/texmfs/install
package repository: http://mirrors.sjtug.sjtu.edu.cn/ctan/systems/win32/miktex/tm/packages/
package repository digest: 0051892e82e2f6a3249012fd042a9b51
going to download 8630983 bytes
going to install 29 file(s) (1 package(s))
downloading http://mirrors.sjtug.sjtu.edu.cn/ctan/systems/win32/miktex/tm/packages/l3kernel.tar.lzma...
8.63 MB, 424.85 Mbit/s
extracting files from l3kernel.tar.lzma...
======================================================================

(/miktex/.miktex/texmfs/install/tex/latex/l3kernel/expl3.sty
(/miktex/.miktex/texmfs/install/tex/latex/l3kernel/expl3-code.tex
======================================================================
starting package maintenance...
installation directory: /miktex/.miktex/texmfs/install
package repository: http://mirrors.sjtug.sjtu.edu.cn/ctan/systems/win32/miktex/tm/packages/
package repository digest: 0051892e82e2f6a3249012fd042a9b51
going to download 236231 bytes
going to install 11 file(s) (1 package(s))
downloading http://mirrors.sjtug.sjtu.edu.cn/ctan/systems/win32/miktex/tm/packages/unicode-data.tar.lzma...
0.24 MB, 620.44 Mbit/s
extracting files from unicode-data.tar.lzma...
======================================================================
)

! LaTeX Error: File `l3backend-pdfmode.def' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: def)

Enter file name:
```

I think that [this](https://tex.stackexchange.com/questions/499082/file-l3backend-pdfmode-def-not-found-when-loading-expl3) is the problem because building the document just worked fine when I built the docker image on my own.

Building the docker image on my own resulted in MiKTeX `v2.9.7050` living inside the container instead of `v2.9.6980`.

Have a nice day! 😃

**Comment by gw0** [comment]
Yes, a fresh official rebuild would be nice. Latest tag `2.9.6990` has some issues, like:

```
ERROR - Error: Found biblatex control file version 3.6, expected version 3.5.
This means that your biber (2.12) and biblatex (3.13a) versions are incompatible.
See compat matrix in biblatex or biber PDF documentation.
```

**Comment by nanmu42** [comment]
I built an unofficial one, which might help: https://hub.docker.com/r/nanmu42/miktex-docker .

**Comment by gw0** [comment]
@nanmu42 Have you tested your unofficial version? Because your version gives the same error, but with different versions:

```
ERROR - Error: Found biblatex control file version 3.6, expected version 3.7.
This means that your biber (2.14) and biblatex (3.13a) versions are incompatible.
See compat matrix in biblatex or biber PDF documentation.
```

**Comment by nanmu42** [comment]
Could you provide a minimal example to reproduce this error?

**Comment by gw0** [comment]
After performing a clean reinstall, cleaning all auxiliary files, and some debugging, I managed to get both Docker images to work. Because TeX packages are constantly changing and MiKTeX downloads them on demand, one **always has to update MiKTeX repositories before using any image**.

The solution is to use the official Docker image `miktex/miktex` like that:

```bash
$ sudo docker run -it -v $(pwd):/miktex/work miktex/miktex bash
$ mpm --admin --update
$ latexmk example.tex
```

Consider adding `mpm --admin --update` to documentation. Cleaning `/miktex/.miktex` and all auxiliary files is also a good troubleshooting step.

If anyone is interested in a trivial example that uses XeLaTeX and Biber to compile to PDF:

```
% example.tex
\documentclass[a4paper,english]{article}
\RequirePackage{biblatex}
\addbibresource{example.bib}
\begin{document}
This is some text.
\cite{Foo2019}
\end{document}
```

```
% example.bib
@misc{Foo2019,
author = {Foo, Bar},
title = {{Learning to foo the bar}},
year = {2019}
}
```

```
# .latexmkrc
$bibtex_fudge=0;
# use xelatex - xdv -> pdf - not working due to bugs in 4.61
$pdf_mode=5;
&alt_tex_cmds;
```

**Comment by yM1ndst0rM** [comment]
Bumping for visibility: An update of the official build on dockerhub is very appreciated

**Comment by rose-a** [comment]
Yep, the docker hub image is outdated since August!
