### ISSUE TITLE
pdftex does not find memory dump

### ISSUE THREAD

**Issue by 1kastner** [MiKTeX/docker-miktex#17]
First I believed only my local installation (Windows 10) got corrupted but the same happens in the docker image on a Linux machine:

```
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.6980)

Sorry, but pdftex did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  /miktex/.miktex/texmfs/data/miktex/log/pdftex.log
root@2a243aa2498b:/miktex/work# tail /miktex/.miktex/texmfs/data/miktex/log/pdftex.log

The log file hopefully contains the information to get MiKTeX going again:

  /miktex/.miktex/texmfs/data/miktex/log/initexmf.log

2020-05-13 19:32:56,576Z FATAL pdftex - The memory dump file could not be found.
2020-05-13 19:32:56,576Z FATAL pdftex - Info: fileName="pdftex.fmt"
2020-05-13 19:32:56,576Z FATAL pdftex - Source: Libraries/MiKTeX/TeXAndFriends/texmfapp.cpp
2020-05-13 19:32:56,576Z FATAL pdftex - Line: 689
2020-05-13 19:32:56,576Z INFO  pdftex - finishing with exit code 1
```

Is there anything wrong about the current installer, is that sheer bad luck, or is there something obvious I miss? Out of the sudden I can't use MiKTeX anymore!

**Comment by vincentb1** [comment]
I have the same issue. I realized this as the docker MiKTeX fails to install package geometry.
When I try to install it manually by opening a console on the docker image, then I fails on `pdftex geometry.dtx` with the same sort of error.

**Comment by vincentb1** [comment]
Just for information, I could work around this by fooling `geometry.dtx` into thinking that it is not compiled by latex.  What `geometry.dtx` does, is that if the format is `LaTeX2e`, then the manual is generated, and otherwise the exteraction occurs, since the docstrip program can be ran both by pdftex and by pdflatex, I just did the extraction like that:
```
pdflatex '\def\fmtname{tricky}\input{geometry.dtx}'
```

**Comment by 1kastner** [comment]
Thank you very much for that hint!
