### ISSUE TITLE
Multiple errors while running pdflatex main.tex

### ISSUE THREAD

**Issue by pablodz** [MiKTeX/docker-miktex#28]
Hello there,
I know that this repository is not popular. However, I find really useful to don't use Win10.

I have some problems while running `pdflatex main.tex` and those are the logs running, also I'll attach the file that I'm trying to build. I tried the code with normal version of miktex on Win10, and everything worked as expected.

To reproduce the error run these commands on Ubuntu

```bash
git clone https://github.com/ZurMaD/tesis_pregrado_pucp
cd tesis_pregrado_pucp
cd Latex/trabajo-de-investigacion-2
# Here is where all the data is stored to run main.tex as usual
docker run -ti \
            -v miktex:/miktex/.miktex \
            -v `pwd`:/miktex/work \
            miktex/miktex \
            pdflatex main.tex
```

getting this error

```bash
pdflatex: warning: running with administrator privileges
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.6980)

Sorry, but pdflatex did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  /miktex/.miktex/texmfs/data/miktex/log/pdflatex.log
```

Those are the log files: 
[logs.zip](https://github.com/MiKTeX/docker-miktex/files/6529027/logs.zip)

and I got them with, for example
```bash
sudo docker run -ti \
            -v miktex:/miktex/.miktex \
            -v `pwd`:/miktex/work \
            miktex/miktex \
            cat   /miktex/.miktex/texmfs/data/miktex/log/initexmf.log >> initexmf.log
```

Please, let me know if I can help and thanks in advance!

**Comment by pablodz** [comment]
Fixed with https://github.com/pablodz/miktex-docker-stable

**Comment by msrumon** [comment]
> Fixed with https://github.com/pablodz/miktex-docker-stable

I can confirm this *DOES NOT* work on WSL2.

```text
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./entrypoint.sh": stat ./entrypoint.sh: no such file or directory: unknown.
```

Additionally, can you please contribute to the original repo instead of creating one by yourself? Thank you very much for your time and effort.

**Comment by pablodz** [comment]
I started using typs app, MikTek is too old
