### ISSUE TITLE
Outdated Dockerfile

### ISSUE THREAD

**Issue by keesj** [MiKTeX/docker-miktex#37]
Hi,

The docker file in this repository looks quite outdated.  I made a few changes (but still do not have the full system running).
1) Switched to Jammy (Latest LTS of ubuntu)

1) Modified 
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
RUN echo "deb http://miktex.org/download/ubuntu jammy universe" | tee /etc/apt/sources.list.d/miktex.list

to 

RUN curl -fsSL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xD6BC243565B2087BC3F897C9277A7293F59E4889" | gpg --dearmor -o /usr/share/keyrings/miktex.gpg \
    && echo "deb [arch=amd64, signed-by=/usr/share/keyrings/miktex.gpg] http://miktex.org/download/ubuntu jammy universe" | tee /etc/apt/sources.list.d/miktex.list 

This method requires curl to be installed but at least does not use the soon deprecated apt-key tool.

3) Modified the mpm calls by calls using miktex packages function

4)  Modified the containter to add a user and run the setup as user. This appears to be the currently preffered way?

**Comment by keesj** [comment]
I still have #36 with this setup

**Comment by keesj** [comment]
Additionally is appears the #4 discusses **NOT** using a USER. .. so does the install need to be make "shared"  or installed under the root user? running as root does gives a lot of warnings

**Comment by jdoubleu** [comment]
Maybe you could submit your changes in a PR?

**Comment by keesj** [comment]
hi @jdoubleu: I was not able to either use this image nor create my own e.g. I  do not have the full system running

**Comment by PHPirates** [comment]
> hi @jdoubleu: I was not able to either use this image nor create my own e.g. I do not have the full system running

Weird, I uploaded my updated image to [github](https://github.com/Hannah-Sten/TeXiFy-IDEA/pkgs/container/TeXiFy-IDEA%2Fmiktex) and it's working fine.

**Comment by irishismyname** [comment]
I was having all kinds of weird problems with the image on Docker hub (digest ebd838f3) and almost gave up. However, after I built the image from [b29fc32](https://github.com/MiKTeX/docker-miktex/commit/b29fc32cfd57cc98f4d2a32f32933f7d96c6ce73) (current HEAD as of writing) and it worked as expected. It seems like this repo could use a GitHub action to build & push the image 🤔.
