### ISSUE TITLE
How do I install languages?

### ISSUE THREAD

**Issue by shyd** [MiKTeX/docker-miktex#5]
Hi,

when building with `pdflatex` on windows, everything works like expected with

```
\usepackage[T1]{fontenc}
\usepackage[ngerman]{babel}
```

but using the docker image, the following error occurs in the log:

```
Package babel Warning: No hyphenation patterns were preloaded for
(babel)                the language `German (new orthography)' into the format.

(babel)                Please, configure your TeX system to add them and
(babel)                rebuild the format. Now I will use the patterns
(babel)                preloaded for \language=0 instead on input line 43.
```

How do I install more languages via commandline like I can do with the windows tool in the Languages tab?

Thanks

**Comment by carlodri** [comment]
one idea (untested): open a interactive docker session and try to add the language from there?
Some (maybe) useful links: [mpm](https://docs.miktex.org/manual/mpm.html)  and https://texfaq.org/FAQ-newlang

**Comment by shyd** [comment]
Thanks for the input. This is not an option, because I use CI/CD services to build the document.
Anyways, I ended up using a full TexLive installation.
