### ISSUE TITLE
`USER miktex` breaks ability to run commands as root

### ISSUE THREAD

**Issue by nils-werner** [MiKTeX/docker-miktex#6]
None of the [other](https://github.com/LuisAlejandro/dockershelf/blob/master/debian/jessie/Dockerfile) [Docker](https://github.com/docker-library/python/blob/caba688d74997c2d063907e35f5439b1b1811d9e/3.6/jessie/Dockerfile) [images](https://github.com/perl/docker-perl/blob/a5c2d6c896807e9c1beec4ebac01c7f30c075bf0/5.026.001-64bit/Dockerfile) I have encountered use

    USER some_user

but simply run all commands as `root`. Is there a specific reason why you are not doing that, too?

I am trying to use this image for a [GitLab CI](https://docs.gitlab.com/ee/ci/yaml/README.html) build, and since I am not `root` I cannot run `apt-get` in my build scripts anymore.

**Comment by KOLANICH** [comment]
Any progress on it?

**Comment by 1kastner** [comment]
Well, there are several projects which also switch the user, e.g. the docker Jupyter Notebook images.
You can maybe simply create your own image and push it to dockerhub?
It could be great if you share the link afterwards!

**Comment by KOLANICH** [comment]
It wouldn't be an official image and I would have to maintain it.

**Comment by nils-werner** [comment]
> Well, there are several projects which also switch the user, e.g. the docker Jupyter Notebook images.

[Yes, and they have massive problems because of it.](https://github.com/jupyter/docker-stacks/issues?utf8=%E2%9C%93&q=is%3Aissue+NB_UID+)

There really is no reason to manually set a `USER` in this otherwise very simple Docker image. If *you* want to run this as a specific user, you could simply [use the `--user` flag when doing `docker run`](https://docs.docker.com/engine/reference/run/#user)

**Comment by edocevoli** [comment]
The commands are now executed as `root`.

To execute as the current user, you can pass options `-e MIKTEX_GID=$(id
-g)` and `-e MIKTEX_UID=$(id -u)` to the Docker `run` command.
