### ISSUE TITLE
Docker Hub image has outdated local package database

### ISSUE THREAD

**Issue by raikesy** [MiKTeX/docker-miktex#7]
I'm trying to use this docker image to compile a document that uses the fontawesome5 package. It appears that miktex won't download it from the miktex repo and so latex looks for the package locally and the compilation fails.

I have found a work around of running `mpm --update-db` before trying to compile the document which does fix the issue but is it possible to refresh the docker image so this isn't necessary?

Is this the intended behaviour? As miktex uses a rolling release model perhaps the image should update monthly rather than annually to keep more up-to-date with the miktex package repository out of the box

**Comment by edocevoli** [comment]
A new image has been released.

**Comment by debuglevel** [comment]
This issue does still exist. And it is not really solved by relasing a new image once the old begins to break. I suggest to add at least a note in the docker hub file pointing users to manually updating the database:
```
docker run -ti -v miktex:/miktex/.miktex miktex/miktex mpm --update-db
```

Actually I would suggest that a `mpm --update-db` should be called before all other commands if the database is older than a certain time.
