### ISSUE TITLE
Install make along with MiKTeX to use make

### ISSUE THREAD

**Issue by milkpirate** [MiKTeX/docker-miktex#8]
Some repos can benefit from haveing `make` available. E.g. LaTeX docs which were generated via Sphinx do include a `Makefile` for easy compile to PDF.

```
- RUN apt-get install miktex -y
+ RUN apt-get install make miktex -y
```

will do the trick hopefully.

Also adding `sudo` and `adduser miktex sudo` would it make possible to adjust the container in CIs without building it all on your own. So:

```
- RUN apt-get install miktex -y
+ RUN apt-get install make miktex sudo -y
...
+ RUN adduser miktex sudo
```

**Comment by 1kastner** [comment]
Maybe you could just fork this project and offer your own version?
I would most likely pull your image from docker hub.

**Comment by milkpirate** [comment]
Hey,

I have made my own [dockerfile](https://gitlab.com/milkpirate/dockerfiles/blob/master/Dockerfile.miktex) because I am using the gitlabs CI with their/my own docker registry (where I pull my images from). Hope it helps eventhough its not pullable container.

**Comment by 1kastner** [comment]
Thanks a lot, it's a great help!
`mpm --install amsfonts` is kind of what I was looking for in #9.
In https://docs.miktex.org/manual/mpm.html there are the listed options.

**Comment by milkpirate** [comment]
I guess miktex is installing missing tex packages on the fly whenever they are needed... but in the CI many things are differen :) good to know.

Will close that issue, since I found a solution for myself.

**Comment by 1kastner** [comment]
It does install them on-the-fly but that is not what I want it to do because it is kind of expensive. Therefore the image should be delivered with batteries included. 
Thank you very much for sharing your dockerfile!
